name = "zephyr-fee-agg-imp"

[[tables]]
name = "avgfee"

[[tables.columns]]
name = "time_st"
col_type = "BYTEA"

[[tables.columns]]
name = "classic"
col_type = "BYTEA"

[[tables.columns]]
name = "contracts"
col_type = "BYTEA"

[[tables.columns]]
name = "other"
col_type = "BYTEA"

[[tables.columns]]
name = "avg_s"
col_type = "BYTEA"

[[tables.columns]]
name = "avg_c"
col_type = "BYTEA"